# Generated by Django 5.0.2 on 2024-02-23 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Stickers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stickersName', models.CharField(max_length=50)),
                ('stickersDescription', models.CharField(max_length=100)),
                ('fileName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=255)),
                ('caption', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('geolocID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.geolocation')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StickersUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stickersID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.stickers')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
