# Generated by Django 5.0.1 on 2024-03-15 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='type',
            field=models.CharField(blank=True, default='noneType', max_length=20),
        ),
        migrations.AlterField(
            model_name='postsuser',
            name='avatarInUse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_pic', to='database.stickers'),
        ),
    ]
