# Generated by Django 5.0.2 on 2024-02-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geolocation',
            name='position',
        ),
        migrations.AddField(
            model_name='geolocation',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='geolocation',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
